#pragma once

#define MASTER_LEFT

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_WPM_ENABLE

#define OLED_TIMEOUT 60000
#define OLED_BRIGHTNESS 128

#define DYNAMIC_KEYMAP_LAYER_COUNT 5

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

